steps:

# This step stops the nfs pod
- name: 'gcr.io/cloud-builders/kubectl'
  id: Stop Production Pods
  args:
    - 'scale'
    - 'StatefulSet'
    - 'nfs-constellation-prod'
    - '--replicas=0'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'  

# This step deploys the application in Kubernetes
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: Deploy to Production Environment
  args:
    - run
    - --filename=prod.yaml
    - --image=gcr.io/$PROJECT_ID/nfs-constellation:$_SHORT_SHA
    - --location=us-east1-b
    - --cluster=cluster-1

# This step starts the nfs pod
- name: 'gcr.io/cloud-builders/kubectl'
id: Scale Production Pods
args:
  - 'scale'
  - 'StatefulSet'
  - 'nfs-constellation-prod'
  - '--replicas=1'
env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'    