steps:

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/nfs-confluence:$SHORT_SHA'
    - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/nfs-confluence:$SHORT_SHA'

# This step stops the nfs pods
- name: 'gcr.io/cloud-builders/kubectl'
  id: Stop Pods
  args:
    - 'scale'
    - 'StatefulSet'
    - 'nfs-confluence-prod'
    - '--replicas=0'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'  

# This step deploys the application in Kubernetes
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: Deploy To Prod Environment
  args:
    - run
    - --filename=prod.yaml
    - --image=gcr.io/$PROJECT_ID/nfs-confluence:$SHORT_SHA
    - --location=us-east1-b
    - --cluster=cluster-1

# This step starts the nfs pods
- name: 'gcr.io/cloud-builders/kubectl'
  id: Scale Pods
  args:
    - 'scale'
    - 'StatefulSet'
    - 'nfs-constellation-prod'
    - '--replicas=1'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'    
