apiVersion: v1
kind: Service
metadata:
  name: nfs-constellation-test
  labels:
    app: nfs-constellation-test
spec:
  ports:
  - port: 2049
    name: nfs-constellation-test
  selector:
    app: nfs-constellation-test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-constellation-test
spec:
  serviceName: nfs-constellation-test
  replicas: 1
  selector:
    matchLabels:
      app: nfs-constellation-test
  template:
    metadata:
      labels:
        app: nfs-constellation-test
    spec:
      containers:
      - name: nfs-dev
        image: gcr.io/constellation-275522/nfs
        ports:
        - containerPort: 2049
          name: nfs-constellation-test
        resources:
          limits:
            cpu: ".5"
            memory: "500Mi"
          requests:
            cpu: ".25"
            memory: "250Mi"
        volumeMounts:
        - name: nfs-constellation-test
          mountPath: /nfsshare
        livenessProbe:
          tcpSocket:
            port: 2049
          initialDelaySeconds: 3
          periodSeconds: 3
        securityContext:
          privileged: true          
  volumeClaimTemplates:
  - metadata:
      name: nfs-constellation-test
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi

   
